### ISSUE TITLE
abort() when using "timeserver" configuration

### ISSUE THREAD

**Issue by svenihoney** [muwerk/munet#2]
If I use the "timeserver" in `net.json` together with the demo project, I get the following error on an ESP32 in the call to `configTime`:
```
Reading net.json
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1442 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x40088869 on core 1

Backtrace: 0x4008c434:0x3ffb1c30 0x4008c665:0x3ffb1c50 0x40088869:0x3ffb1c70 0x4013867a:0x3ffb1cb0 0x40138956:0x3ffb1cd0 0x401278d8:0x3ffb1cf0 0x40127941:0x3ffb1d10 0x4012eb39:0x3ffb1d30 0x4012eb5e:0x3ffb1d50 0x40127737:0x3ffb1d70 0x400db27f:0x3ffb1d90 0x400d49fa:0x3ffb1e00 0x400d4fca:0x3ffb1f50 0x400dbd0b:0x3ffb1fb0 0x40088b7d:0x3ffb1fd0
```
If I remove the "timeserver" config or move the block containing `configTime` into the block after `WiFi.status() == WL_CONNECTED`, the error disappears.

**Comment by domschl** [comment]
Thanks for the good analysis of the bug! I will prepare a new release after some testing.

Related [esp32 issue](https://github.com/espressif/arduino-esp32/issues/2632).

**Comment by domschl** [comment]
Release 0.1.8 that should fix the issue is being published to Arduino and Platformio library managers. Tx!
